# Benchmarks, analysis and inspection of the SolarCube task and datasets

Given geostationary satellite images, physics-based simulations of solar irradiance, and geographic information for a specific region on Earth over the preceding 24 hours at a given point in time, the goal of the SolarCube task is to predict the total shortwave solar radiation reaching the Earth’s horizontal surface over the next 24 hours, with a temporal resolution of 15 minutes and a spatial resolution of 5 kilometers.

Improving solutions for this forecasting task enables power system operators to more accurately plan and dispatch energy resources, thereby reducing dependence on backup storage systems, transmission grid expansions, and expensive peak-load power plants. Accurate solar irradiance forecasting is therefore a key enabler for integrating large shares of fluctuating and uncertain solar generation into highly renewable power systems.

The SolarCube task is multimodal and combines geostationary satellite imagery, gridded spatio-temporal weather and irradiance data, physics-based simulation outputs, and geographic information describing the observed regions.

The SolarCube task is formulated as a supervised learning problem, where models are trained to predict future shortwave solar radiation from historical multimodal observations. Depending on the sub-task, the learning objective involves spatial, temporal, or spatio-temporal generalization across different geographic regions and forecasting horizons.

We define six forecasting sub-task datasets that share the same multimodal input representation but differ along two principal dimensions: <br>
(i) whether the prediction target corresponds to point-based or area-based solar radiation, and <br>
(ii) whether the test set contains unseen time stamps, unseen geographic regions, or both. 

This design enables the systematic evaluation of temporal, spatial, and spatio-temporal generalization capabilities of forecasting models.


## Overview
---
1. Creating benchmarks
2. Analysing characteristics
3. Inspecting aigrids data
4. Inspecting processed data
5. Inspecting raw data

In [1]:
import os
import sys

import pandas as pd
import h5py

import utils
import aigrids

# set the path to your configuration file here.
path_cfg = '../config_arsam.yml'

# load the configuration file and show us
cfg = utils.parse_config(path_cfg)
cfg

## 1. Creating benchmarks

In [ ]:
# TODO

## 2. Analysing characteristics

In [ ]:
# TODO

## 3. Inspecting aigrids data

In [2]:
taskdata = load.load_task(
    'SolarCube', 
    'odd_time_area_3h',
    path_root,
    data_frac = 0.01
)

Processing 'odd_time_area_3h' for 'SolarCube'...
Using the full dataset with data_frac=1 set by user.
Continuing with max_workers=1024
Continuing with max_workers_download=4
Preparing local data directory for 'SolarCube'...
Error fetching file list: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets/AI4Climate/SolarCube/tree/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4b95ce1f60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Found 0 files to manage (download if needed).
Data for AI4Climate/SolarCube is now available at ../../donti_group_shared/AI4Climate/processed/SolarCube.

Preparing subtask 'odd_time_area_3h'...
Data for odd_time_area_3h successfully loaded.

In [3]:
taskdata

{'train_data': 0, 'val_data': 0, 'test_data': 0}

## 4. Inspecting processed data

In [ ]:
# SKIP

## 5. Inspecting raw data

In [44]:
# set paths to exemplar data
path_raw_data_root = os.path.join(cfg['path_root'], 'raw', 'SolarCube')
path_cm = os.path.join(path_raw_data_root, 'SolarCube_2018_1_cm.hdf')
path_ir133 = os.path.join(path_raw_data_root, 'SolarCube_2018_1_ir133.hdf')
path_ssr = os.path.join(path_raw_data_root, 'SolarCube_2018_1_ssr.hdf')
path_sza = os.path.join(path_raw_data_root, 'SolarCube_2018_1_sza.hdf')
path_vis047 = os.path.join(path_raw_data_root, 'SolarCube_2018_1_vis047.hdf')
path_vis086 = os.path.join(path_raw_data_root, 'SolarCube_2018_1_vis086.hdf')
path_missing_index_1 = os.path.join(path_raw_data_root, 'index', '1_2018_missing_index.csv')

# set paths to general data
path_sitelist = os.path.join(path_raw_data_root, 'SolarCube_sitelist.csv')
path_insitu = os.path.join(path_raw_data_root, 'SolarCube_insitu.csv')

In [ ]:
# load exemplar data
data_cm = h5py.File(path_cm, 'r').get('cm')[:]
data_ir133 = h5py.File(path_ir133, 'r').get('ir133')[:]
data_ssr = h5py.File(path_ssr, 'r').get('ssr')[:]
data_sza = h5py.File(path_sza, 'r').get('sza')[:]
data_vis047 = h5py.File(path_vis047, 'r').get('vis047')[:]
data_vis086 = h5py.File(path_vis086, 'r').get('vis086')[:]

# load general data
sitelist = pd.read_csv(path_sitelist)
insitu = pd.read_csv(path_insitu)
missing_index = pd.read_csv(path_missing_index_1)

In [29]:
data_ssr.shape

(35040, 120, 120)

In [30]:
data_cm.shape

(35040, 120, 120)

In [31]:
data_ir133.shape

(35040, 120, 120)

In [32]:
data_sza.shape

(35040, 120, 120)

In [33]:
data_vis047.shape

(35040, 120, 120)

In [34]:
data_vis086.shape

(35040, 120, 120)

In [37]:
sitelist

,id,name,lats,lons,network,fLine,fCol,elev,timezone,tile_id,lat_ulcnr,lon_ulcnr,lat_lrcnr,lon_lrcnr,time_offset,test
0,1,bon,40.050,-88.370,SURFRAD,60,60,213.0000,America/Chicago,1,43.05,-91.37,37.05,-85.37,-6.0,0
1,2,fpk,48.310,-105.100,SURFRAD,60,60,623.3125,America/Denver,2,51.31,-108.10,45.31,-102.10,-7.0,0
2,3,gwn,34.250,-89.870,SURFRAD,60,60,101.0625,America/Chicago,3,37.25,-92.87,31.25,-86.87,-6.0,0
3,4,dra,36.620,-116.020,SURFRAD,60,60,998.0625,America/Los_Angeles,4,39.62,-119.02,33.62,-113.02,-8.0,0
4,5,psu,40.720,-77.930,SURFRAD,60,60,375.5625,America/New_York,5,43.72,-80.93,37.72,-74.93,-5.0,1
5,6,sxf,43.730,-96.620,SURFRAD,60,60,476.3125,America/Chicago,6,46.73,-99.62,40.73,-93.62,-7.0,0
6,7,tbl,40.120,-105.240,SURFRAD,60,60,1651.5625,America/Denver,7,43.12,-108.24,37.12,-102.24,-7.0,1
7,8,FLO,-27.533,-48.517,BSRN,109,70,55.0000,America/Sao_Paulo,8,-24.00,-54.00,-30.00,-48.00,-4.0,0
8,9,LRC,37.104,-76.387,BSRN,32,97,4.2500,America/New_York,9,42.00,-78.00,36.00,-72.00,-5.0,1
9,10,ASP,-23.798,133.888,BSRN,37,115,548.0625,Australia/Darwin,10,-18.00,132.00,-24.00,138.00,9.0,0
10,11,COC,-12.193,96.835,BSRN,16,3,3.0625,Indian/Cocos,11,-12.00,96.00,-18.00,102.00,6.0,1
11,12,DWN,-12.424,130.893,BSRN,97,8,25.9375,Australia/Darwin,12,-12.00,126.00,-18.00,132.00,8.0,0
12,13,FUA,33.582,130.375,BSRN,87,48,8.0625,Asia/Tokyo,13,36.00,126.00,30.00,132.00,8.0,0
13,14,HOW,22.554,88.306,BSRN,86,28,6.5000,Asia/Kolkata,14,24.00,84.00,18.00,90.00,6.0,0
14,15,ISH,24.337,124.163,BSRN,83,113,11.5000,Asia/Tokyo,15,30.00,120.00,24.00,126.00,8.0,0
15,16,LAU,-45.045,169.689,BSRN,33,60,352.5000,Pacific/Auckland,16,-42.00,168.00,-48.00,174.00,11.0,0
16,17,NEW,-32.884,151.729,BSRN,34,57,19.6875,Australia/Sydney,17,-30.00,150.00,-36.00,156.00,10.0,0
17,18,SAP,43.060,141.328,BSRN,66,98,20.5625,Asia/Tokyo,18,48.00,138.00,42.00,144.00,9.0,1
18,19,TAT,36.058,140.126,BSRN,42,118,28.1250,Asia/Tokyo,19,42.00,138.00,36.00,144.00,9.0,0

In [38]:
insitu

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0,0.0,0.0,34.6,0.0,0.0,0.0,NaN,0.0,298.0,59.0,517.0,35.0,NaN,109.0,1051.0,985.0,49.0,329.0
1,0.0,0.0,0.0,36.4,0.0,0.0,0.0,NaN,0.0,304.0,61.0,696.0,33.0,NaN,110.0,1052.0,983.0,51.0,332.0
2,0.0,0.0,0.0,41.5,0.0,0.0,0.0,NaN,0.0,310.0,66.0,262.0,34.0,NaN,101.0,1053.0,987.0,52.0,335.0
3,0.0,0.0,0.0,45.2,0.0,0.0,0.0,NaN,0.0,316.0,69.0,247.0,37.0,NaN,89.0,1053.0,992.0,55.0,337.0
4,0.0,0.0,0.0,51.3,0.0,0.0,0.0,NaN,0.0,322.0,71.0,251.0,41.0,NaN,80.0,1055.0,992.0,59.0,339.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525595,0.0,0.0,0.0,46.1,0.0,0.0,0.0,NaN,0.0,773.0,112.0,444.0,246.0,0.0,35.0,NaN,NaN,90.0,322.0
525596,0.0,0.0,0.0,42.9,0.0,0.0,0.0,NaN,0.0,776.0,115.0,333.0,255.0,0.0,34.0,NaN,NaN,94.0,326.0
525597,0.0,0.0,0.0,39.9,0.0,0.0,0.0,NaN,0.0,779.0,119.0,433.0,263.0,0.0,34.0,NaN,NaN,101.0,327.0
525598,0.0,0.0,0.0,37.3,0.0,0.0,0.0,NaN,0.0,781.0,122.0,453.0,274.0,0.0,34.0,NaN,NaN,109.0,316.0
525599,0.0,0.0,0.0,35.3,0.0,0.0,0.0,NaN,0.0,784.0,126.0,477.0,292.0,0.0,35.0,NaN,NaN,120.0,332.0

In [39]:
data_ir133

array([[[24099, 24139, 24189, ..., 23996, 24080, 24222],
        [24097, 24122, 24187, ..., 24458, 24468, 24397],
        [24133, 24113, 24160, ..., 24491, 24468, 24426],
        ...,
        [25245, 25271, 25255, ..., 25332, 25319, 25328],
        [25271, 25259, 25255, ..., 25322, 25327, 25338],
        [25244, 25243, 25253, ..., 25333, 25339, 25332]],

       [[24099, 24116, 24163, ..., 23891, 23902, 23925],
        [24086, 24104, 24159, ..., 24138, 24183, 24106],
        [24112, 24091, 24147, ..., 24320, 24385, 24399],
        ...,
        [25242, 25260, 25250, ..., 25317, 25306, 25305],
        [25269, 25258, 25247, ..., 25310, 25313, 25322],
        [25232, 25236, 25237, ..., 25326, 25322, 25323]],

       [[24092, 24093, 24152, ..., 23864, 23874, 23876],
        [24089, 24087, 24142, ..., 23903, 23922, 23930],
        [24111, 24072, 24135, ..., 23969, 23954, 24044],
        ...,
        [25224, 25252, 25234, ..., 25304, 25290, 25280],
        [25254, 25242, 25225, ..., 25299, 25297, 25304],
        [25222, 25227, 25224, ..., 25307, 25308, 25316]],

       ...,

       [[24634, 24471, 24326, ..., 25990, 26047, 26059],
        [24690, 24582, 24456, ..., 25862, 26014, 26080],
        [24773, 24740, 24653, ..., 25966, 26163, 26154],
        ...,
        [24585, 24933, 25740, ..., 23649, 23583, 23165],
        [24405, 25213, 25781, ..., 23830, 23709, 23219],
        [24347, 25037, 25620, ..., 23799, 23791, 23056]],

       [[24351, 24552, 24754, ..., 25430, 25553, 25462],
        [24454, 24598, 24770, ..., 25307, 25337, 25365],
        [24690, 24684, 24735, ..., 24983, 25193, 25308],
        ...,
        [26237, 26397, 26010, ..., 23530, 23439, 23512],
        [26100, 26391, 26132, ..., 23614, 23654, 23663],
        [25623, 26269, 26078, ..., 23856, 23789, 23507]],

       [[25028, 25113, 25006, ..., 25178, 25229, 25334],
        [25194, 25075, 24900, ..., 25235, 25286, 25391],
        [25168, 25012, 24623, ..., 25462, 25297, 25497],
        ...,
        [25330, 25201, 25334, ..., 22982, 22534, 22422],
        [25665, 25244, 25256, ..., 23609, 22759, 22433],
        [25734, 25332, 24399, ..., 23769, 23120, 22604]]], dtype=int16)

In [42]:
35040/ 24 / 365

4.0